name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'pnpm'
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check (Build)
        run: pnpm run build

      - name: Run tests
        run: |
          # Check if the 'test' script exists before attempting to run it
          if pnpm test >/dev/null 2>&1; then
            pnpm test # 💡 Changed to pnpm
          else
            echo "No test script defined; skipping tests"
          fi
